name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소를 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. .npmrc 파일 생성
      - name: Create .npmrc
        run: |
          echo "@goorm-dev:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CONTEST_NPM_TOKEN }}" >> .npmrc

      # 3. .env.local 파일 생성
      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_API_URL=http://localhost:5000" > .env.local
          echo "NEXT_PUBLIC_ENCRYPTION_KEY=${{ secrets.CONTEST_ENCRYPTION_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_PASSWORD_SALT=${{ secrets.CONTEST_PASSWORD_SALT }}" >> .env.local

      # 4. Docker 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: timepresent95
          password: ${{ secrets.CONTEST_DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: timepresent95/contest-fe:latest
